//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.10 at 08:48:04 PM GST 
//


package au.com.quaysystems.doh.towings.web.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for FlightId complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlightId"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="_hasAirportCodes" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="_hasFlightDesignator" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="_hasScheduledTime" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="airlineDesignatorField" type="{http://schemas.datacontract.org/2004/07/WorkBridge.Modules.AMS.AMSIntegrationAPI.Mod.Intf.DataTypes}ArrayOfLookupCode"/&gt;
 *         &lt;element name="airportCodeField" type="{http://schemas.datacontract.org/2004/07/WorkBridge.Modules.AMS.AMSIntegrationAPI.Mod.Intf.DataTypes}ArrayOfLookupCode"/&gt;
 *         &lt;element name="flightKindField" type="{http://schemas.datacontract.org/2004/07/WorkBridge.Modules.AMS.AMSIntegrationAPI.Mod.Intf.DataTypes}FlightKind"/&gt;
 *         &lt;element name="flightNumberField" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="scheduledDateField" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightId", namespace = "http://schemas.datacontract.org/2004/07/WorkBridge.Modules.AMS.AMSIntegrationAPI.Mod.Intf.DataTypes", propOrder = {
    "hasAirportCodes",
    "hasFlightDesignator",
    "hasScheduledTime",
    "airlineDesignatorField",
    "airportCodeField",
    "flightKindField",
    "flightNumberField",
    "scheduledDateField"
})
public class FlightId {

    @XmlElement(name = "_hasAirportCodes")
    protected boolean hasAirportCodes;
    @XmlElement(name = "_hasFlightDesignator")
    protected boolean hasFlightDesignator;
    @XmlElement(name = "_hasScheduledTime")
    protected boolean hasScheduledTime;
    @XmlElement(required = true, nillable = true)
    protected ArrayOfLookupCode airlineDesignatorField;
    @XmlElement(required = true, nillable = true)
    protected ArrayOfLookupCode airportCodeField;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected FlightKind flightKindField;
    @XmlElement(required = true, nillable = true)
    protected String flightNumberField;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar scheduledDateField;

    /**
     * Gets the value of the hasAirportCodes property.
     * 
     */
    public boolean isHasAirportCodes() {
        return hasAirportCodes;
    }

    /**
     * Sets the value of the hasAirportCodes property.
     * 
     */
    public void setHasAirportCodes(boolean value) {
        this.hasAirportCodes = value;
    }

    /**
     * Gets the value of the hasFlightDesignator property.
     * 
     */
    public boolean isHasFlightDesignator() {
        return hasFlightDesignator;
    }

    /**
     * Sets the value of the hasFlightDesignator property.
     * 
     */
    public void setHasFlightDesignator(boolean value) {
        this.hasFlightDesignator = value;
    }

    /**
     * Gets the value of the hasScheduledTime property.
     * 
     */
    public boolean isHasScheduledTime() {
        return hasScheduledTime;
    }

    /**
     * Sets the value of the hasScheduledTime property.
     * 
     */
    public void setHasScheduledTime(boolean value) {
        this.hasScheduledTime = value;
    }

    /**
     * Gets the value of the airlineDesignatorField property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfLookupCode }
     *     
     */
    public ArrayOfLookupCode getAirlineDesignatorField() {
        return airlineDesignatorField;
    }

    /**
     * Sets the value of the airlineDesignatorField property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfLookupCode }
     *     
     */
    public void setAirlineDesignatorField(ArrayOfLookupCode value) {
        this.airlineDesignatorField = value;
    }

    /**
     * Gets the value of the airportCodeField property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfLookupCode }
     *     
     */
    public ArrayOfLookupCode getAirportCodeField() {
        return airportCodeField;
    }

    /**
     * Sets the value of the airportCodeField property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfLookupCode }
     *     
     */
    public void setAirportCodeField(ArrayOfLookupCode value) {
        this.airportCodeField = value;
    }

    /**
     * Gets the value of the flightKindField property.
     * 
     * @return
     *     possible object is
     *     {@link FlightKind }
     *     
     */
    public FlightKind getFlightKindField() {
        return flightKindField;
    }

    /**
     * Sets the value of the flightKindField property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightKind }
     *     
     */
    public void setFlightKindField(FlightKind value) {
        this.flightKindField = value;
    }

    /**
     * Gets the value of the flightNumberField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightNumberField() {
        return flightNumberField;
    }

    /**
     * Sets the value of the flightNumberField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightNumberField(String value) {
        this.flightNumberField = value;
    }

    /**
     * Gets the value of the scheduledDateField property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getScheduledDateField() {
        return scheduledDateField;
    }

    /**
     * Sets the value of the scheduledDateField property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setScheduledDateField(XMLGregorianCalendar value) {
        this.scheduledDateField = value;
    }

}
