//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.10 at 08:48:04 PM GST 
//


package au.com.quaysystems.doh.towings.web.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FlightUpdateInformationExtended complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlightUpdateInformationExtended"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://schemas.datacontract.org/2004/07/WorkBridge.Modules.AMS.AMSIntegrationAPI.Mod.Intf.DataTypes}FlightUpdateInformation"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="codeSharesUpdateField" type="{http://schemas.datacontract.org/2004/07/WorkBridge.Modules.AMS.AMSIntegrationAPI.Mod.Intf.DataTypes}ArrayOfCodeShareFlightIdentifier"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightUpdateInformationExtended", namespace = "http://schemas.datacontract.org/2004/07/WorkBridge.Modules.AMS.AMSIntegrationAPI.Mod.Intf.DataTypes", propOrder = {
    "codeSharesUpdateField"
})
public class FlightUpdateInformationExtended
    extends FlightUpdateInformation
{

    @XmlElement(required = true, nillable = true)
    protected ArrayOfCodeShareFlightIdentifier codeSharesUpdateField;

    /**
     * Gets the value of the codeSharesUpdateField property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfCodeShareFlightIdentifier }
     *     
     */
    public ArrayOfCodeShareFlightIdentifier getCodeSharesUpdateField() {
        return codeSharesUpdateField;
    }

    /**
     * Sets the value of the codeSharesUpdateField property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfCodeShareFlightIdentifier }
     *     
     */
    public void setCodeSharesUpdateField(ArrayOfCodeShareFlightIdentifier value) {
        this.codeSharesUpdateField = value;
    }

}
