//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.10 at 08:48:04 PM GST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sita.aero/ams6-xml-api-webservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package au.com.quaysystems.doh.towings.web.ws;
