//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.10 at 08:48:04 PM GST 
//


package au.com.quaysystems.doh.towings.web.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PropertyValue complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PropertyValue"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="codeContextField" type="{http://schemas.datacontract.org/2004/07/WorkBridge.Modules.AMS.AMSIntegrationAPI.Mod.Intf.DataTypes}CodeContext"/&gt;
 *         &lt;element name="codeContextFieldSpecified" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="propertyNameField" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="valueField" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PropertyValue", namespace = "http://schemas.datacontract.org/2004/07/WorkBridge.Modules.AMS.AMSIntegrationAPI.Mod.Intf.DataTypes", propOrder = {
    "codeContextField",
    "codeContextFieldSpecified",
    "propertyNameField",
    "valueField"
})
public class PropertyValue {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected CodeContext codeContextField;
    protected boolean codeContextFieldSpecified;
    @XmlElement(required = true, nillable = true)
    protected String propertyNameField;
    @XmlElement(required = true, nillable = true)
    protected String valueField;

    /**
     * Gets the value of the codeContextField property.
     * 
     * @return
     *     possible object is
     *     {@link CodeContext }
     *     
     */
    public CodeContext getCodeContextField() {
        return codeContextField;
    }

    /**
     * Sets the value of the codeContextField property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeContext }
     *     
     */
    public void setCodeContextField(CodeContext value) {
        this.codeContextField = value;
    }

    /**
     * Gets the value of the codeContextFieldSpecified property.
     * 
     */
    public boolean isCodeContextFieldSpecified() {
        return codeContextFieldSpecified;
    }

    /**
     * Sets the value of the codeContextFieldSpecified property.
     * 
     */
    public void setCodeContextFieldSpecified(boolean value) {
        this.codeContextFieldSpecified = value;
    }

    /**
     * Gets the value of the propertyNameField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyNameField() {
        return propertyNameField;
    }

    /**
     * Sets the value of the propertyNameField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyNameField(String value) {
        this.propertyNameField = value;
    }

    /**
     * Gets the value of the valueField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueField() {
        return valueField;
    }

    /**
     * Sets the value of the valueField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueField(String value) {
        this.valueField = value;
    }

}
