//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.10 at 08:48:04 PM GST 
//


package au.com.quaysystems.doh.towings.web.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sessionToken" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="slotRequestId" type="{http://schemas.datacontract.org/2004/07/WorkBridge.Modules.AMS.AMSIntegrationAPI.Mod.Intf.DataTypes}SlotRequestIdentifier" minOccurs="0"/&gt;
 *         &lt;element name="updateSlotRequestValues" type="{http://schemas.datacontract.org/2004/07/WorkBridge.Modules.AMS.AMSIntegrationAPI.Mod.Intf.DataTypes}ArrayOfPropertyValue" minOccurs="0"/&gt;
 *         &lt;element name="createSlotRequestValues" type="{http://schemas.datacontract.org/2004/07/WorkBridge.Modules.AMS.AMSIntegrationAPI.Mod.Intf.DataTypes}ArrayOfArrayOfPropertyValue" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sessionToken",
    "slotRequestId",
    "updateSlotRequestValues",
    "createSlotRequestValues"
})
@XmlRootElement(name = "SplitSlotRequest")
public class SplitSlotRequest {

    @XmlElementRef(name = "sessionToken", namespace = "http://www.sita.aero/ams6-xml-api-webservice", type = JAXBElement.class, required = false)
    protected JAXBElement<String> sessionToken;
    @XmlElementRef(name = "slotRequestId", namespace = "http://www.sita.aero/ams6-xml-api-webservice", type = JAXBElement.class, required = false)
    protected JAXBElement<SlotRequestIdentifier> slotRequestId;
    @XmlElementRef(name = "updateSlotRequestValues", namespace = "http://www.sita.aero/ams6-xml-api-webservice", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfPropertyValue> updateSlotRequestValues;
    @XmlElementRef(name = "createSlotRequestValues", namespace = "http://www.sita.aero/ams6-xml-api-webservice", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfArrayOfPropertyValue> createSlotRequestValues;

    /**
     * Gets the value of the sessionToken property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSessionToken() {
        return sessionToken;
    }

    /**
     * Sets the value of the sessionToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSessionToken(JAXBElement<String> value) {
        this.sessionToken = value;
    }

    /**
     * Gets the value of the slotRequestId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link SlotRequestIdentifier }{@code >}
     *     
     */
    public JAXBElement<SlotRequestIdentifier> getSlotRequestId() {
        return slotRequestId;
    }

    /**
     * Sets the value of the slotRequestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link SlotRequestIdentifier }{@code >}
     *     
     */
    public void setSlotRequestId(JAXBElement<SlotRequestIdentifier> value) {
        this.slotRequestId = value;
    }

    /**
     * Gets the value of the updateSlotRequestValues property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfPropertyValue }{@code >}
     *     
     */
    public JAXBElement<ArrayOfPropertyValue> getUpdateSlotRequestValues() {
        return updateSlotRequestValues;
    }

    /**
     * Sets the value of the updateSlotRequestValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfPropertyValue }{@code >}
     *     
     */
    public void setUpdateSlotRequestValues(JAXBElement<ArrayOfPropertyValue> value) {
        this.updateSlotRequestValues = value;
    }

    /**
     * Gets the value of the createSlotRequestValues property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfArrayOfPropertyValue }{@code >}
     *     
     */
    public JAXBElement<ArrayOfArrayOfPropertyValue> getCreateSlotRequestValues() {
        return createSlotRequestValues;
    }

    /**
     * Sets the value of the createSlotRequestValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfArrayOfPropertyValue }{@code >}
     *     
     */
    public void setCreateSlotRequestValues(JAXBElement<ArrayOfArrayOfPropertyValue> value) {
        this.createSlotRequestValues = value;
    }

}
